"""rfmesh-dsss -- DSSS directional-comms DSP (ADR-025).

Pure-Python physical layer for the directional comms link described in
ADR-021 (comms-first reframing) and ADR-019 (antenna rendezvous).
Builds: m-sequence PN generation (length-1023 default, PG ~30 dB), BPSK
modulation, spread/despread, matched-filter correlation, chip/symbol
timing recovery, framing (preamble + sync + header + payload + CRC),
and link-budget honesty.

Invariant B5: pure. No network, no file I/O beyond vendor data tables
at import (none exist), no subprocess, no SDR access. End-to-end
testable in pytest against ``rfmesh-sdr``'s ``SyntheticTransmitter`` +
``loopback_channel`` (delivered in Iter 3) with zero hardware --
mirror of the simulator-first model documented in ARCHITECTURE.md §4.

Workspace-discipline reminder (WD-2): every new function in this
package requires a golden-file test in ``tests/golden/``. The golden
artefacts are deterministically generated by
``tests/golden_generator.py`` so a future contributor can regenerate
them with one command and diff against the checked-in versions.

ITER 1 (current) ships PN sequence, BPSK modulation, spread/despread,
and link-budget honesty -- everything needed for a clean spread ->
despread round-trip with the canonical length-1023 m-sequence.
Iter 2 fills correlation / timing / framing; Iter 3 wires the
synthetic transmitter + loopback channel; Iter 4+ orchestrates at
the node layer.
"""

from __future__ import annotations

from .exceptions import (
    AcquisitionFailedError,
    DsssError,
    FrameDecodeError,
    InvalidPnSequenceError,
)
from .link_budget import ber_theoretical_bpsk, processing_gain_db
from .modulation import bpsk_demodulate, bpsk_modulate
from .pn_sequence import cyclic_autocorrelation, generate_m_sequence
from .spreading import despread, spread

__all__ = [
    "AcquisitionFailedError",
    "DsssError",
    "FrameDecodeError",
    "InvalidPnSequenceError",
    "ber_theoretical_bpsk",
    "bpsk_demodulate",
    "bpsk_modulate",
    "cyclic_autocorrelation",
    "despread",
    "generate_m_sequence",
    "processing_gain_db",
    "spread",
]
