"""rfmesh-dsss -- DSSS directional-comms DSP (ADR-025).

Pure-Python physical layer for the directional comms link described in
ADR-021 (comms-first reframing) and ADR-019 (antenna rendezvous).
Builds: m-sequence PN generation (length-1023 default, PG ~30 dB), BPSK
modulation, spread/despread, matched-filter correlation, chip/symbol
timing recovery, framing (preamble + sync + header + payload + CRC),
and link-budget honesty.

Invariant B5: pure. No network, no file I/O beyond vendor data tables
at import (none exist), no subprocess, no SDR access. End-to-end
testable in pytest against ``rfmesh-sdr``'s ``SyntheticTransmitter`` +
``loopback_channel`` (delivered in Iter 3) with zero hardware --
mirror of the simulator-first model documented in ARCHITECTURE.md §4.

Workspace-discipline reminder (WD-2): every new function in this
package requires a golden-file test in ``tests/golden/``. The golden
artefacts are deterministically generated by
``tests/golden_generator.py`` (Iter 1+) so a future contributor can
regenerate them with one command and diff against the checked-in
versions.

ITER 0 (this file lands as part of ADR-025 acceptance) ships the
package SKELETON only. Module bodies are stubs; public API is not
re-exported yet. Iter 1 fills PN / modulation / spreading; Iter 2
fills correlation / timing / framing; Iter 3 wires the synthetic
transmitter + loopback channel; Iter 4+ orchestrates at the node
layer.

WHAT WILL BE EXPORTED (once Iter 1+ fill the bodies)
----------------------------------------------------
* PN sequence: ``generate_m_sequence``, LFSR primitives.
* BPSK: ``bpsk_modulate``, ``bpsk_demodulate``.
* Spread: ``spread`` (bit -> chip), ``despread`` (correlate with PN).
* Correlation: ``matched_filter``, ``acquire_preamble``.
* Timing: ``recover_chip_timing``, ``correct_carrier_phase``.
* Framing: ``encode_frame``, ``decode_frame`` (CRC-16 internal).
* Link budget: ``processing_gain_db``, ``ber_theoretical_bpsk``.
* Exceptions: ``DsssError`` and subclasses.

Nothing is exported yet from this ``__init__`` because Iter 0 ships
no functionality. The skeleton existing under mypy + import-linter +
ruff is the deliverable; functionality lands behind the iteration
gates documented in the implementation plan
(``docs/dsss/potrzebujplanuimplementacjirozszerzenidempotentplum.md``).
"""

from __future__ import annotations
