"""rfmesh-dsss -- DSSS directional-comms DSP (ADR-025).

Pure-Python physical layer for the directional comms link described in
ADR-021 (comms-first reframing) and ADR-019 (antenna rendezvous).
Builds: m-sequence PN generation (length-1023 default, PG ~30 dB), BPSK
modulation, spread/despread, matched-filter correlation, chip/symbol
timing recovery, framing (preamble + sync + header + payload + CRC),
and link-budget honesty.

Invariant B5: pure. No network, no file I/O beyond vendor data tables
at import (none exist), no subprocess, no SDR access. End-to-end
testable in pytest against ``rfmesh-sdr``'s ``SyntheticTransmitter`` +
``loopback_channel`` (delivered in Iter 3) with zero hardware --
mirror of the simulator-first model documented in ARCHITECTURE.md §4.

Workspace-discipline reminder (WD-2): every new function in this
package requires a golden-file test in ``tests/golden/``. The golden
artefacts are deterministically generated by
``tests/golden_generator.py`` so a future contributor can regenerate
them with one command and diff against the checked-in versions.

ITER 2 (current) ships PN sequence, BPSK modulation, spread/despread,
framing (preamble + sync + header + payload + CRC-16), matched-filter
preamble acquisition, block-mode carrier-phase recovery, and
link-budget honesty -- the full offline DSSS pipeline minus the SDR
edge. Iter 3 wires the synthetic transmitter + loopback channel and
adds chip-rate timing recovery for the realtime SDR path; Iter 4+
orchestrates at the node layer.
"""

from __future__ import annotations

from .correlation import (
    DEFAULT_AMBIGUITY_RATIO,
    DEFAULT_THRESHOLD_RATIO,
    acquire_preamble,
    matched_filter,
)
from .exceptions import (
    AcquisitionFailedError,
    DsssError,
    FrameDecodeError,
    InvalidPnSequenceError,
)
from .framing import (
    BROADCAST_DST,
    CRC_LEN_BITS,
    FIXED_OVERHEAD_BITS,
    HEADER_LEN_BITS,
    PREAMBLE_LEN_BITS,
    SYNC_HAMMING_TOLERANCE,
    SYNC_WORD_HEX,
    SYNC_WORD_LEN_BITS,
    FrameContents,
    decode_frame,
    encode_frame,
    find_sync_word,
)
from .link_budget import ber_theoretical_bpsk, processing_gain_db
from .modulation import bpsk_demodulate, bpsk_modulate
from .pn_sequence import cyclic_autocorrelation, generate_m_sequence
from .spreading import despread, spread
from .timing import correct_carrier_phase, estimate_carrier_phase

__all__ = [
    "BROADCAST_DST",
    "CRC_LEN_BITS",
    "DEFAULT_AMBIGUITY_RATIO",
    "DEFAULT_THRESHOLD_RATIO",
    "FIXED_OVERHEAD_BITS",
    "HEADER_LEN_BITS",
    "PREAMBLE_LEN_BITS",
    "SYNC_HAMMING_TOLERANCE",
    "SYNC_WORD_HEX",
    "SYNC_WORD_LEN_BITS",
    "AcquisitionFailedError",
    "DsssError",
    "FrameContents",
    "FrameDecodeError",
    "InvalidPnSequenceError",
    "acquire_preamble",
    "ber_theoretical_bpsk",
    "bpsk_demodulate",
    "bpsk_modulate",
    "correct_carrier_phase",
    "cyclic_autocorrelation",
    "decode_frame",
    "despread",
    "encode_frame",
    "estimate_carrier_phase",
    "find_sync_word",
    "generate_m_sequence",
    "matched_filter",
    "processing_gain_db",
    "spread",
]
